credentials:
  earthdata:
    user:
    pswd:
skeleton:
  year:
    min: 2015
    max: 2023
  week:
    min: 1
    max: 53
  region: [
    'AD',
    'AE',
    'AF',
    'AG',
    'AI',
    'AL',
    'AM',
    'AO',
    'AR',
    'AS',
    'AT',
    'AU',
    'AW',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BL',
    'BM',
    'BN',
    'BO',
    'BQ',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CF',
    'CG',
    'CH',
    'CI',
    'CK',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CU',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'EH',
    'ER',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FK',
    'FM',
    'FO',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GF',
    'GG',
    'GH',
    'GI',
    'GL',
    'GM',
    'GN',
    'GP',
    'GQ',
    'GR',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IM',
    'IN',
    'IQ',
    'IR',
    'IS',
    'IT',
    'JE',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KP',
    'KR',
    'KW',
    'KY',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MF',
    'MG',
    'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MQ',
    'MR',
    'MS',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NU',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PF',
    'PG',
    'PH',
    'PK',
    'PL',
    'PM',
    'PR',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RE',
    'RO',
    'RS',
    'RU',
    'RW',
    'SA',
    'SB',
    'SC',
    'SD',
    'SE',
    'SG',
    'SH',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    'ST',
    'SV',
    'SX',
    'SY',
    'SZ',
    'TC',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TK',
    'TL',
    'TM',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VA',
    'VC',
    'VE',
    'VG',
    'VI',
    'VN',
    'VU',
    'WF',
    'WS',
    'XK',
    'YE',
    'YT',
    'ZA',
    'ZM',
    'ZW'
]
output_region: [
    #1'AD',
    'AE',
    'AF',
    #1'AG',
    #1'AI',
    'AL',
    'AM',
    'AO',
    'AR',
    #1'AS',
    'AT',
    'AU',
    #1'AW',
    'AZ',
    'BA',
    #1'BB',
    'BD',
    'BE',
    #4'BF',
    'BG',
    #1'BH',
    #2'BI',
    'BJ',
    #1'BL',
    #1'BM',
    'BN',
    'BO',
    #1'BQ',
    'BR',
    #3'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    #4'CD',
    #4'CF',
    #4'CG',
    'CH',
    #4'CI',
    #1'CK',
    'CL',
    #4'CM',
    'CN',
    #2'CO',
    'CR',
    'CU',
    #1'CV',
    #1'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    #1'DM',
    'DO',
    'DZ',
    #5'EC',
    'EE',
    'EG',
    'EH',
    #2'ER',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FK',
    #1'FM',
    'FO',
    'FR',
    #4'GA',
    'GB',
    #1'GD',
    'GE',
    'GF',
    #1'GG',
    'GH',
    #1'GI',
    'GL',
    'GM',
    #5'GN',
    #1'GP',
    #4'GQ',
    'GR',
    'GT',
    #1'GU',
    'GW',
    #2'GY',
    #1'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    #1'IM',
    'IN',
    'IQ',
    'IR',
    'IS',
    'IT',
    #1'JE',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    #1'KI',
    #2'KM',
    #1'KN',
    'KP',
    'KR',
    'KW',
    #1'KY',
    'KZ',
    'LA',
    'LB',
    #1'LC',
    #1'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    #1'MC',
    'MD',
    'ME',
    #1'MF',
    'MG',
    #1'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    #1'MO',
    #1'MP',
    #1'MQ',
    'MR',
    #1'MS',
    #1'MT',
    #2'MU',
    #1'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    #0'NA',
    'NC',
    #4'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    #1'NR',
    #1'NU',
    'NZ',
    'OM',
    #4'PA',
    #2'PE',
    #1'PF',
    'PG',
    'PH',
    'PK',
    'PL',
    #1'PM',
    'PR',
    'PS',
    'PT',
    #1'PW',
    'PY',
    'QA',
    #1'RE',
    'RO',
    'RS',
    'RU',
    #2'RW',
    'SA',
    'SB',
    #1'SC',
    'SD',
    'SE',
    'SG',
    #1'SH',
    'SI',
    'SK',
    #5'SL',
    #1'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    #1'ST',
    #2'SV',
    #1'SX',
    'SY',
    'SZ',
    #1'TC',
    'TD',
    #4'TG',
    'TH',
    'TJ',
    #1'TK',
    'TL',
    'TM',
    'TN',
    #1'TO',
    'TR',
    'TT',
    #1'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    #1'VA',
    #1'VC',
    'VE',
    #1'VG',
    #1'VI',
    'VN',
    #3'VU',
    #1'WF',
    #1'WS',
    #1'XK',
    'YE',
    #1'YT',
    'ZA',
    'ZM',
    'ZW'
]
